development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://xbcykuxixhahvi:31988ededd628d8b889c6b870ee87fe6b1815b2a6978ad88d2a94ca7a2a128be@ec2-184-73-189-221.compute-1.amazonaws.com:5432/d49q0det09rabs
  

